src/app/page.tsx, src/components/common/Caption.tsx, src/components/common/Input.tsx
input 속성 caption 이름 변경
input 속성 caption 이름 변경
=> [QJ5-22] input 속성 caption 이름 변경

src/components/common/index.ts
common 폴더에 있는 여러 컴포넌트 index.ts에 묶어서 export 진행
=> [QJ5-27] common 컴포넌트 index.ts로 내보내기

src/app/layout.tsx, src/app/page.tsx
모든 페이지가 동일한 디자인 (배경색, 양 옆 패딩 등)에 대해서 루트 레이아웃에 적용
- 수정 사항 있으면 말씀해주세요.!
=> [QJ5-39] 페이지 레이아웃 디자인 적용

src/components/common/Input.tsx, src/components/common/Label.tsx
=> [QJ5-40]  인풋 공통 rem 변경

src/components/common/Caption.tsx, src/components/common/Input.tsx, src/components/common/Label.tsx
input 공통 컴포넌트 이슈 수정
- suffix 버튼 위치 수정
- caption 위치 수정
쓰면서 문제 있으면 언제든지 얘기해주세요!
=> [QJ5-46] 인풋 컴포넌트 이슈 수정

src/components/layout/Header.tsx, src/routes/path.ts
모든 라우트 경로를 한 파일에서 관리하여 오타 방지 및 관리가 용이하도록 했습니다!
=> [QJ5-47] 모든 라우트 경로를 상수로 지정

src/app/(home)/page.tsx
=> [QJ5-57] svg?component 수정

src/components/layout/Header.tsx
헤더 컴포넌트 z-index가 낮아서 다른 컴포넌트가 보이는 오류 수정
=> fix: 헤더 컴포넌트 z-index 수정

src/hooks/use-draggable.ts
useDraggble hook 에 use client 추가
=> useDraggble hook 에 use client 추가

src/app/(discovery)/discovery/_components/DiscoverySection.tsx, src/components/common/Alert.tsx, src/components/common/Button.tsx, src/components/common/Modal.tsx, src/components/common/index.ts
- 공통으로 사용될 것 같은 Alert 컴포넌트를 생성했습니다.
- Modal 컴포넌트의 z-index를 수정했습니다. (z-10  ->  z-50)
- **variant**
- checkButton : 확인 alert (window alert랑 비슷하다고 생각하시면 됩니다.)
- linkButton : 링크 alert (버튼 클릭 시 링크 이동)
- fnButton : 실행 alert (버튼 클릭 시 함수 실행)
- **title**
- Alert 제목
- **subText**
- 옵셔널 값
- 내용 텍스트
- 띄어쓰기 있는 글씨 적을 때, 백틱 안에 넣어주시면 됩니다.
- **buttonText**
- 버튼 내용
- **link**
- **variant가 linkButton일 때 사용**, 이동할 링크 작성
- `link="/login"`
- **onClick**
- **variant가 fnButton일 때 사용**, 실행할 함수 작성
- `onClick={() => console.log("삭제 완료")}`
- **subButtonText**
- **variant가 fnButton일 때 사용**, 취소 버튼 텍스트 작성
- `subButtonText="취소"`
<details>
<summary>확인 Alert</summary>
```js
<Alert
variant="checkButton"
title="인증링크를 전송했습니다."
subText={`작성한 이메일 주소로 인증메일을 전송했습니다.
메일 확인 후 회원가입을 계속 진행해주세요.`}
buttonText="확인"
/>
```
</details> …
=> [QJ5-59] Alert 컴포넌트 생성

package-lock.json, package.json, src/app/(home)/_components/SimpleReportCard.tsx, src/app/(home)/news.tsx, src/app/(home)/page.tsx, src/components/common/SimpleRadarChart.tsx
메인 페이지 리포트 컴포넌트 UI
뉴스 컴포넌트 더미데이터 추가 구현
메인 페이지 리포트 컴포넌트 UI
뉴스 컴포넌트 더미데이터 추가 구현
=> [QJ5-66] 메인 페이지 리포트 컴포넌트  & 뉴스 컴포넌트 더미 추가

src/app/(news)/news/[newsId]/_components/index.tsx
=> [QJ5-75] fix: 겹치는 FAB버튼 제거

src/app/[lang]/(home)/news.tsx, src/app/[lang]/(home)/page.tsx, src/components/common/List/NewsItem.tsx
=> [QJ5-76] 메인페이지 디자인 수정

next-auth.d.ts, src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx, src/app/api/auth/find-email/route.ts, src/auth.ts
- 로그인시 제공되는 session 부분의 국가, 회원탈퇴시 필요한 정보 추가 작업
- 로그인 세션 정보 → 언어 추가
- 로그인/회원가입시 DB 조회시 (is_delete) 추가 조회
- 닉네임 DB 조회시 (is_delete) 추가 조회
- [feature/kma/QJ5-103] 작업이랑 동일합니다. 충돌이 났는데 해결하다 너무 꼬여서 다시 PR 요청드립니다.
=> [QJ5-103] 로그인/회원가입 추가 작업 

src/app/[lang]/(discovery)/discovery/_components/DiscoveryNews.tsx, src/app/[lang]/(discovery)/discovery/_components/DiscoveryStocks.tsx, src/app/[lang]/(discovery)/discovery/_components/RecentSearches.tsx, src/app/[lang]/(home)/home/page.tsx, src/app/[lang]/(mystock)/mystock/page.tsx, src/app/[lang]/(news)/news/[newsId]/_components/RelatedStocks.tsx, src/app/api/chat/route.ts
=> fix: build 에러 해결

src/actions/stock.ts, src/app/[lang]/(report)/report/_components/ReportHeader.tsx, src/lib/api.ts, src/types/ApiType.ts
api type 이 isDataArray false 일때 타입이 정상적으로 추론되도록 수정
=> fix: api type

src/actions/stock.ts, src/app/[lang]/(report)/report/_components/StockChart.tsx, src/app/[lang]/(report)/report/_components/StockChartSection.tsx, src/app/[lang]/(report)/report/_components/index.tsx, src/app/api/stocks/[...code]/route.ts, src/app/api/stocks/[code]/route.ts, src/types/StockDataType.ts, src/utils/calculate-period.ts
주식 차트 기능 활성화
주식 차트를 일, 주, 월, 분기, 년 으로 나눠서 가져오도록 수정
=> [QJ5-109] 주식 차트 기능 활성화

src/app/[lang]/(auth)/_components/CommonAgreeLayout.tsx, src/app/[lang]/(auth)/withdraw/page.tsx, src/app/[lang]/(mypage)/mypage/_components/VerifyModal.tsx, src/app/[lang]/(report)/report/_components/StockDetail.tsx, src/hooks/use-get-action.ts
=> [QJ5-118] 빌드 이슈 수정 - 타입 에러 등

src/actions/news.ts, src/app/[lang]/(news)/news/page.tsx
=> hotfix: error in news

src/app/[lang]/(news)/news/[newsId]/_components/AiSummary.tsx, src/app/api/chat/route.ts, src/app/api/report/stock-analysis/[code]/route.ts, src/components/common/ChatBox.tsx
=> [QJ5-138] 뉴스 요약하기 버튼 disabled 추가

src/auth.ts
몽구스를 사용한 조회 -> fetch 백엔드 통신
미들웨에서 몽구스를 사용하여 언어를 가져오는 코드에서 npm run build 시에 Edge에서 실행되면 런타임 오류가 발생
참고 : https://nextjs.org/docs/messages/edge-dynamic-code-evaluation
- 미들웨어에서 auth.ts를 가져오는데, auth에서 몽구스를 사용하고 있어서 오류가 발생
- 몽구스를 통한 조회를 전부 백엔드 통신으로 변경
- 백엔드 pull 받아서 진행해주시면 됩니다.
- 급하게 만든 코드라 좀 더러우니 나중에 수정해주세요...
=> [QJ5-139] 몽구스를 사용한 조회 -> fetch 백엔드 통신

src/actions/auth.ts, src/auth.ts, src/types/AuthType.ts
=> [QJ5-142] 일반회원 auth의 session 오류 

src/app/[lang]/(mypage)/mypage/_components/LanguageSettingMain.tsx, src/app/[lang]/(mypage)/mypage/_components/WithdrawModal.tsx
- 로그아웃 후, 유저의 로그인 전 언어설정을 불러오지 못하는 오류를 해결했습니다.
- 백엔드도 최신화 해주셔야 합니다! `develop` 브랜치
- 섞인 커밋은 회원탈퇴 시 버튼 disabled 처리한 부분입니다
=> [QJ5-143] 언어설정 오류 수정

src/app/[lang]/(home)/home/news.tsx, src/app/[lang]/(news)/news/[newsId]/_components/AiSummary.tsx, src/app/api/chat/route.ts, src/app/api/stock-price/sse/[reutersCode]/route.ts, src/components/common/ChatBox.tsx, src/constants/stockCodes.ts, src/hooks/use-stock-price.ts, src/utils/debounce.ts
=> [QJ5-Tool] 챗봇 툴 기능 추가

src/components/common/DescriptionWithLineBreaks.tsx
=> [QJ5-145] 뉴스 디테일 페이지 - 줄바꿈 두번하도록 수정

src/auth.ts
=> [QJ5-146] auth session name 추가 

src/components/common/ChatBox.tsx
=> [QJ5-138] ai tools ui 수정

src/app/[lang]/(mystock)/mystock/_components/MyStockModalSection.tsx, src/app/[lang]/(mystock)/mystock/_components/MyStockPopularSearches.tsx, src/app/[lang]/(mystock)/mystock/_components/MyStockSearchResult.tsx, src/app/[lang]/(mystock)/mystock/_components/_skeleton/SearchItemSkeleton.tsx
관심 주식 페이지 검색 박스 적용 및 기타 UI 수정
- 관심 주식 페이지 검색 박스 적용
- 검색 후 결과 스켈레톤 적용
- 인기 검색어 렌더링 수정
https://github.com/user-attachments/assets/f2bd1f4f-6c54-4550-b497-f8488e91cd00
=> [QJ5-150] 관심 주식 페이지 검색 박스 적용 및 기타 UI 수정

src/app/[lang]/(mypage)/mypage/_components/LanguageSettingMain.tsx, src/app/[lang]/layout.tsx, src/middleware.ts, src/utils/cookies.ts
- 특정 페이지로 이동이 되지 않는 오류를 수정했습니다.
- 로그인 직후 언어 설정이 제대로 되지 않는 오류를 수정했습니다.
- 터미널에 계속 `unable to find next-intl locale` 오류 문구가 뜨는데(고친 줄 알고 커밋했는데 아니었어요...), 기능 상 문제는 없지만 매우 거슬리네요😯 남은 작업 마무리하고 고쳐보도록 하겠습니다.
=> [QJ5-158] 특정 페이지 이동불가 미들웨어 오류 수정

src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
=> [QJ5-162] 잘못된 병합된 import 삭제

src/app/[lang]/(report)/report/[stockReutersCode]/layout.tsx, src/app/[lang]/layout.tsx, src/middleware.ts
미들웨어 수정해서 제가 할때는 문제없이 되도록 수정해줬는데 혹시 모르기 때문에 QA 부탁드립니다.
=> [QJ5-161] 미들웨어 locale path regex 수정

src/app/[lang]/(auth)/_components/CommonLayout.tsx, src/app/[lang]/(auth)/withdraw/page.tsx, src/app/[lang]/(home)/home/_components/recent-news.tsx, src/app/[lang]/(news)/news/_components/index.tsx
=> [QJ5-164] 뉴스 페이지 이슈 수정

src/app/[lang]/(home)/home/_components/recent-news.tsx
=> [QJ5-165] 최신 뉴스 파라미터 빈값 전달 이슈

src/app/[lang]/(mystock)/mystock/_components/MyStockBody.tsx, src/app/[lang]/(mystock)/mystock/_components/MyStockFooter.tsx, src/app/[lang]/(mystock)/mystock/_components/MyStockHeader.tsx, src/app/[lang]/(mystock)/mystock/_components/MyStockHeaderButton.tsx, src/app/[lang]/(mystock)/mystock/_components/MyStockModalSection.tsx, src/app/[lang]/(mystock)/mystock/_components/MyStockPopularSearches.tsx, src/app/[lang]/(mystock)/mystock/_components/MyStockRecentSearches.tsx, src/app/[lang]/(mystock)/mystock/_components/MyStockSearchResult.tsx, src/app/[lang]/(mystock)/mystock/_components/SearchItem.tsx, src/app/[lang]/(mystock)/mystock/_components/index.ts, src/components/common/SearchBox.tsx, src/dictionaries/ch.json, src/dictionaries/en.json, src/dictionaries/fr.json, src/dictionaries/jp.json, src/dictionaries/ko.json, src/stores/useRecentSearchStore.ts
- 관심 주식 페이지 다국어 적용 및 버그 수정
- 관심 주식 페이지 다국어 적용
- 관심 주식 추가 및 삭제 시 순서 버그 수정
- 종목 추가를 한 상태인데, '삭제'가 아닌 '추가'로 계속 되어 오류가 발생하는 버그 수정
=> [QJ5-163] 관심 주식 페이지 다국어 적용 및 버그 수정

src/middleware.ts
미들웨어 path regex 수정 - 비로그인시 홈 진입 안되는 이슈
=> [QJ5-166] 미들웨어 path regex 수정 - 비로그인시 홈 진입 안되는 이슈

src/middleware.ts
=> [QJ5-167] 미들웨어 일부 수정

src/app/[lang]/(auth)/account/layout.tsx, src/app/[lang]/(discovery)/discovery/[search]/page.tsx, src/app/[lang]/(discovery)/discovery/layout.tsx, src/app/[lang]/(discovery)/discovery/page.tsx, src/app/[lang]/(home)/home/_components/ai-reports.tsx, src/app/[lang]/(home)/home/_components/news-box.tsx, src/app/[lang]/(home)/home/_components/popular-interest-news.tsx, src/app/[lang]/(home)/home/_components/recent-lookup.tsx, src/app/[lang]/(home)/home/layout.tsx, src/app/[lang]/(home)/layout.tsx, src/app/[lang]/(mypage)/mypage/page.tsx, src/app/[lang]/(report)/report/[stockReutersCode]/layout.tsx, src/app/[lang]/(report)/report/_components/AccumulationBarChart.tsx, src/app/[lang]/(report)/report/_components/ReportHeader.tsx, src/app/[lang]/(report)/report/_components/StockChart.tsx, src/components/common/List/NewsItem.tsx, src/components/common/ReportCardHeader.tsx, src/dictionaries/ch.json, src/dictionaries/en.json, src/dictionaries/fr.json, src/dictionaries/jp.json, src/dictionaries/ko.json
=> [QJ5-171] 각종 이슈 해결 및 메인페이지 국제화 + 챗봇 개선

src/actions/news.ts, src/app/[lang]/(home)/home/_components/popular-interest-news.tsx, src/components/common/Card.tsx
메인 페이지 관심 주식 뉴스 항목 주식 아이콘 안 나오는 버그 수정
=> fix: 메인 페이지 관심 주식 뉴스 항목 주식 아이콘 안 나오는 버그 수정

src/app/[lang]/layout.tsx
=> feat: 네이버, 구글 TXT 레코드 메타 태그 추가

src/app/[lang]/(auth)/account/register/page.tsx, src/app/[lang]/layout.tsx, src/components/common/ChatBox.tsx
=> fix: chatbot error

src/hooks/use-stock-price.ts
=> [HOTFIX] SSE Event Source 최적화 

src/hooks/use-stock-price.ts, src/utils/metadata.ts
=> Merge to Main

src/models/stock-codes-schema.ts, src/scripts/db.ts, src/scripts/generate-stock-codes.ts, src/scripts/run.ts
=> [FEATURE] 타입 생성 스크립트 추가

src/actions/search.ts, src/app/[lang]/(mypage)/mypage/_components/MyPageMain.tsx, src/app/[lang]/(mystock)/mystock/_components/MyStockFooter.tsx, src/app/[lang]/(news)/news/[newsId]/_components/AiSummary.tsx, src/app/globals.css, src/components/common/Button.tsx, src/hooks/use-alert.ts
=> [QJ5-179] 여러가지 버그 수정 및 리팩토링 진행

src/app/[lang]/(home)/home/_components/ai-reports.tsx, src/app/[lang]/(home)/home/page.tsx, src/app/[lang]/(report)/report/_components/StockChart.tsx, src/app/[lang]/(report)/report/_components/StockTooltip.tsx
홈 layout shift 이슈 수정 및 stock chart tooltip 디자인 수정
=> [QJ5-178] 홈 layout shift 이슈 수정 및 stock chart tooltip 디자인 수정

src/app/[lang]/(auth)/_components/SocialLogin.tsx, src/app/[lang]/(home)/home/_components/interest-stocks.tsx, src/app/[lang]/(home)/home/_components/popular-interest-news.tsx, src/app/[lang]/(home)/home/_components/recent-lookup.tsx, src/app/[lang]/(news)/news/[newsId]/_components/AiSummary.tsx, src/app/[lang]/(news)/news/[newsId]/_components/NewsDetail.tsx, src/app/[lang]/(news)/news/[newsId]/_components/RelatedStocks.tsx, src/app/[lang]/(news)/news/_components/NewsInfinityList.tsx, src/components/common/Card.tsx, src/components/common/ChatBot.tsx, src/components/common/CircleSpinner.tsx, src/components/common/List/FindNews.tsx, src/components/common/List/NewsItem.tsx, src/components/common/List/StockItem.tsx, src/components/common/PoPularNews.tsx, src/components/common/StockPrice.tsx, src/components/layout/Header.tsx
=> [QJ5-179] UI/UX 및 버그 수정

src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
=> [QJ5-173] 다국어 stocks 변경으로 인한 side effect

src/app/robots.txt, src/app/sitemap.xml, src/middleware.ts
=> [QJ5-182] 사이트맵, 로봇txt 파일 추가 및 설정

src/app/[lang]/(home)/home/@news/page.tsx, src/app/[lang]/(home)/home/_components/news-box.tsx, src/app/[lang]/(home)/home/layout.tsx, src/app/[lang]/(home)/home/page.tsx
=> [QJ5-183] 메인페이지 최적화2

src/app/[lang]/(home)/home/@news/page.tsx, src/app/[lang]/(home)/home/layout.tsx, src/app/[lang]/(home)/home/page.tsx
=> [QJ5-184] 메인 페이지 에러 및 마이페이지 이슈 수정

src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
=> [QJ5-188] 닉네임 중복 확인 로딩 구현

src/app/[lang]/(mypage)/mypage/_components/PrivacyEditModal.tsx
-[x] 회원탈퇴 버튼 스타일 수정
- 회원탈퇴 버튼 스타일을 수정했습니다.
=> [QJ5-187] 계정정보 수정 하단 회원탈퇴 버튼 스타일 수정

src/actions/stock-analysis.ts, src/app/[lang]/(report)/report/_components/StockChartSection.tsx, src/app/api/ai/stock-analysis/[code]/route.ts, src/app/api/ai/summary/static/route.ts, src/app/api/chat/route.ts, src/app/api/report/stock-analysis/[code]/ai-tool/route.ts, src/components/common/ChatBox.tsx, src/constants/ai-info.ts, src/dictionaries/ch.json, src/dictionaries/en.json, src/dictionaries/fr.json, src/dictionaries/jp.json, src/dictionaries/ko.json, src/lib/db.ts, src/types/NewsDataType.ts
=> [QJ5-183] 챗봇 기능 개선

src/app/[lang]/(report)/report/_components/StockChartSection.tsx, src/app/api/stock/price/sse/[reutersCode]/route.ts
=> hotfix: error in chart
