doksuri5/frontend

- src/app/layout.tsx
- src/components/layout/Header.tsx
레이아웃 헤더 UI 구현
- 피그마에 디자인된 사항으로 헤더 마크업을 구현했습니다.
- 간단한 라우터 이동만 구현했습니다.
- 추후 로그인 로직을 넣으면 됩니다.
- 로그인 X, 메인 페이지
- 로그인 O, 메인 페이지
- 로그인 O, 그 외 페이지
수정해야 될 부분 있으면 말씀해주세요
> [QJ5-28] 헤더 컴포넌트 마크업 및 디자인

- next.config.mjs
- src/components/layout/Header.tsx
- svgr.d.ts
- tsconfig.json
SVG 파일 URL 또는 component로 불러오기 위한 설정 파일 수정
SVG 파일을 불러올 때, 
- 파일 자체를 불러와서 Image 태그에 넣는 경우
- SVG 파일을 컴포넌트로 변환해서 컴포넌트 처럼 사용하는 경우
2가지의 방법이 있는데, 사람마다 사용 방법이 다르기 때문에 오류가 발생할 수 있습니다.
구분하기 위해 컴포넌트로 사용하는 경우는 `.svg` 확장자 뒤에 `?component` 접미사를 붙여 앨리어싱을 건너뛰어 기본 내보내기를 사용할 수 있습니다.
**svg 파일을 Image 태그에 src로 넣는 경우**
`import LargeRect from "@/public/icons/card3Rectangle_large.svg";`
**svg 파일을 컴포넌트로 변환해서 사용하는 경우**
`import LightLogo from "@/public/icons/light_logo.svg?component";`
1. svg 파일을 Image 태그에 src로 넣는 경우
2. svg 파일을 컴포넌트로 변환해서 사용하는 경우
궁금하신 부분 있으시면 말씀해주세요.!
- [next.js에서 svgr 사용법 - 공식문서](https://react-svgr.com/docs/next/) (공식 문서에서 좀 더 직관적으로 사용하기 위해 조금 수정했습니다.)
- [vite, react에서 svg 컴포넌트화](https://velog.io/@yoonth95/SVG-%ED%8C%8C%EC%9D%BC-React-Component%EB%A1%9C-%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0-Vite-Type …
> [QJ5-43] Next에서 SVG 파일 설정 

- src/app/globals.css
- src/components/common/Modal.tsx
- src/components/common/index.ts
- tailwind.config.ts
화면 UI 작성에 사용되는 Modal을 구현했습니다.
<details>
<summary><b>예시 코드</b></summary>
<div markdown="1">
```
"use client";
import { Dropdown, Modal, Button } from "@/components/common";
import { Input } from "@/components/common/Input";
import { useState } from "react";
export default function Home() {
const [isOpen, setIsOpen] = useState(false);
const closeModal = () => setIsOpen(false);
const onChangeSelect = () => {};
return (
<>
<h1 className="bg-background-100">Home Component</h1>
<button className="rounded-[.8rem] bg-blue-700 px-4 py-2 text-white" onClick={() => setIsOpen(true)}>
모달 열기
</button>
<Modal
panelStyle="px-[10.2rem] py-[8rem] rounded-[3.2rem] w-[59rem]"
isOpen={isOpen}
onClose={() => setIsOpen(false)}
title="회원 탈퇴"
titleStyle="heading_3"
closeIcon={true}
>
<div className="mt-[4rem] …
```
> [QJ5-32] Modal 공통 컴포넌트 작성

- src/app/layout.tsx
- src/components/layout/Header.tsx
루트 레이아웃 최대 너비 고정
- 피그마에 디자인된 사항으로 전체 페이지의 화면 구성 최대 너비를 1200px로 고정했습니다.
- 반응형으로 바뀌게 되면 고정 값들 수정해야 됩니다.!
> design: 루트 레이아웃 최대 너비 1200px 고정

- src/app/(home)/error.tsx
- src/app/(home)/page.tsx
- src/app/global-error.tsx
- src/app/loading.tsx
- src/app/not-found.tsx
- src/components/common/Spinner.tsx
- tailwind.config.ts
- not found page
- global error page
- loading page
- spinner
각 페이지 구현
https://github.com/doksuri5/frontend/assets/60169820/aba84ae7-e825-460f-b86a-48a63eae54ce
각 페이지별로 에러 페이지 구현을 할지 global 로 하나로 쓸지 고민이네요
> [QJ5-34] not found & error & loading 페이지 구현

- src/app/(discovery)/discovery/_components/DiscoveryInput.tsx
- src/app/(discovery)/discovery/page.tsx
- src/app/(mystock)/mystock/_components/MyStockBody.tsx
- src/app/(mystock)/mystock/_components/MyStockHeader.tsx
- 관심 주식 페이지 화면 margin-bottom 추가
- 발견 페이지 DiscoveryInput 컴포넌트 useState -> useRef로 수정
> [QJ5-71] 발견 페이지 input 리팩토링 및 관심 주식 페이지 스타일 수정

- src/app/(news)/news/_components/index.tsx
- src/app/(report)/report/[stockReutersCode]/page.tsx
- src/app/(report)/report/_components/AIAnalystReport.tsx
- src/app/(report)/report/_components/ReportHeader.tsx
- src/app/(report)/report/_components/StockAIReport.tsx
- src/app/(report)/report/_components/StockChart.tsx
- src/app/(report)/report/_components/StockChartSection.tsx
- src/app/(report)/report/_components/StockDetail.tsx
- src/app/(report)/report/_components/index.tsx
- src/components/common/Card.tsx
- src/components/common/PoPularNews.tsx
- src/components/common/index.ts
- src/routes/path.ts
- 주가 차트에 사용된 데이터가 어떻게 구성되어있을지 아직 알 수 없어서 3개월 기준으로만 대략 작성해서 구현했습니다.
- 그래서 주가 차트의 버튼도 UI만 구현되어 있습니다.
https://github.com/doksuri5/frontend/assets/55550034/deacf4f0-2729-4753-a715-7c3b485c740b
- 주가 차트 섹션의 y축과 버튼 위치(1일, 3개월...)는 피그마와 다르게 구현한 부분이라서 배치가 괜찮은지 함께 봐주세요!
> [QJ5-65] 리포트 페이지 UI 구현

- src/app/(home)/news.tsx
- src/app/(news)/news/_components/NewsInfinityList.tsx
- src/app/(news)/news/_components/index.tsx
- src/components/common/List/NewsItem.tsx
- src/components/common/PoPularNews.tsx
뉴스 페이지의 카드에 더미데이터를 넣어줬습니다.
뉴스 상세 페이지로 이동하는 부분은 Link태그로 감싸줬습니다. 
근데 PopularNews컴포넌트에 Link컴포넌트로 감싸준 부분이 동작을 안하는데 더 찾아보겠습니다!
공통 컴포넌트 내부에서 Link태그로 감싸도록 추후 리팩토링하겠습니다!
> [QJ5-73] 뉴스 관련 카드, 뉴스에 더미데이터 추가 및 Link태그 추가

- src/app/[lang]/(mypage)/mypage/_components/PolicyContent.tsx
- src/app/[lang]/(mypage)/mypage/_components/PolicyMain.tsx
- src/app/[lang]/(mypage)/mypage/terms/page.tsx
- src/utils/textUtils.tsx
- API를 이용해 이용약관을 DB에서 호출했습니다.
- 데이터의 개행 문자열을 적절히 처리하여 출력했습니다.
- API 호출 실패 시, Alert로 `이용약관을 불러오지 못했습니다.`라는 문구를 유저에게 보여줄지, 혹은 기존에 존재하는 프론트엔드 약관 텍스트로 대체해서 보여줄지 고민입니다.🤔
- 백엔드 URL은 `NEXT_PUBLIC_API_BASE_URL`로 대체하여 작성했습니다. `.env` 파일에 `NEXT_PUBLIC_API_BASE_URL=http://localhost:8080` 추가해 주시면 정상적으로 API 호출이 가능합니다.
> [QJ5-93] 마이페이지 이용약관 API 호출 및 데이터 적용

- src/app/[lang]/(home)/home/_components/SimpleReportCard.tsx
- src/app/[lang]/(mystock)/mystock/_components/MyStockItem.tsx
- src/app/[lang]/(mystock)/mystock/_components/MyStockPopularSearches.tsx
- src/app/[lang]/(mystock)/mystock/_components/SearchItem.tsx
- src/app/[lang]/(report)/report/_components/AIAnalystReport.tsx
- src/app/[lang]/(report)/report/_components/StockAIReport.tsx
- src/app/[lang]/(report)/report/_components/StockDetail.tsx
- src/app/[lang]/(report)/report/_components/index.tsx
- src/components/common/List/StockItem.tsx
- src/utils/stockPriceUtils.ts
- tailwind.config.ts
- 주식 데이터에서 +,-가 아닌 변동이 없을 경우 구현 (텍스트 컬러 변경, 부호와 화살표 기호 제거)
- 종목 AI 리포트에서 변동이 없을 때는 따로 피그마에 나와있는게 없어서, 화살표 기호를 없애고 텍스트 컬러를 중립일 때의 컬러로 변경해두었습니다.
- `getTextColor`함수
- 텍스트 컬러를 지정하는 함수가 겹치기 때문에 `getTextColor`함수 하나로 통일했습니다.
- `formatValueWithIndicator`함수
- 화살표기호가 필요한 주식 데이터는 항상 숫자값과 함께 쓰이기 때문에 내부에서 절댓값처리 후 화살표 기호를 함께 붙인 문자열을 반환하도록 리팩터링했습니다.
- `formatValueWithSign`함수
- 데이터 값이 양수일 경우에는 `+`기호를 별도로 붙여줘야하기 때문에, 내부에서 양수인지 확인 후 `+`기호와 함께 데이터를 반환하도록 리팩터링했습니다.
`getTextColor`에서 `data===0`일 때 텍스트 컬러는 맞게 반환하지만, 실제 tailwind css로 인식을 할 때도 있고 안될 때도 있는 버그가 있었습니다. 그래서 `className`에는 텍스트컬러가 들어가지만 실제로 `font-color`로 반영되지 않았습니다. 그래서 `safelist`에 `getTextColor`함수에 의해 동적으로 지정되는 색상 3개를 모두 지정했습니다.
- 주식데이터가 중립일 때
- +일 때
리팩터링하면서 제 담당이 아닌 홈, 관심주식, 발견 페이지들에도 수정이 생겨서 혹시 이상한 부분이 있는지 확인 부탁드려요! 또 더 좋게 리팩터링하는 방법이 있는지 피드백 부탁드립니다! …
> [QJ5-92] 주식 데이터에서 중립이 있을 경우 처리 추가, 주식 데이터 포맷팅 관련 함수 리팩터링

- src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
formData에 isAgreeCreditInfo, investPropensity 필드 추가 코드가 누락돼서 다시 추가했습니다!!
> [QJ5-117] formData에 isAgreeCreditInfo, investPropensity 필드 추가

- src/app/[lang]/(auth)/withdraw/page.tsx
- src/app/[lang]/(mypage)/mypage/_api/withdrawApi.ts
- src/app/[lang]/(mypage)/mypage/_components/VerifyModal.tsx
- src/app/[lang]/(mypage)/mypage/_components/WithdrawModal.tsx
- src/middleware.ts
- 회원탈퇴 후 메인페이지 이동 시 제대로 메인페이지가 보이지 않는 버그 수정
- 메일 인증 초시계 위치 수정
- 회원탈퇴 시 로딩 추가
- 회원탈퇴 후 메인페이지로 이동할 때 로그인 체크 관련 에러가 발생하는 문제를 수정했습니다.
- 메일 인증 시 초시계의 위치를 입력 필드 내부 오른쪽에 배치시켰습니다.
- 민아님이 구현해주신 토스트를 이용해 회원탈퇴 시 로딩 메시지를 처리했습니다.
x
> [QJ5-122] 회원탈퇴 후 메인페이지 이동 시 버그 수정, 메일 인증 초시계 위치 수정

- src/app/[lang]/(discovery)/discovery/_components/DiscoveryInput.tsx
- src/app/[lang]/(report)/report/_components/index.tsx
https://github.com/user-attachments/assets/c32e04f6-c466-4a3e-a69b-528094bc25c1
검색 영역의 아이콘 클릭시 데이터 통신이 제대로 동작하지만 엔터키 적용시 두번씩 중복으로 이벤트가 발생되면서 제대로 데이터 요청이 되지 않고 있는 것 같아 form 태그로 수정했습니다. 
https://github.com/user-attachments/assets/437b0b87-1566-461a-a7a5-f95e41f2756d
> [QJ5-123] 발견페이지 검색 엔터키 검색 이슈 

- src/actions/news.ts
- src/app/[lang]/(news)/news/_components/index.tsx
- src/components/common/Card.tsx
- src/components/common/List/NewsItem.tsx
- src/components/common/PoPularNews.tsx
뉴스페이지에서 발생하는 버그와 카드의 이미지 비율을 수정했습니다!
- '관심종목관련뉴스'를 클릭했을 때 오류가 발생하고 뉴스 디테일 페이지로 이동하지 않는 에러 수정
- 뉴스 발행 시간 포맷팅 코드 머지하면서 삭제된 것 다시 추가
- '관심종목관련뉴스' 카드에 발행사 추가
- 관심종목관련뉴스' 카드의 발행시간 포맷팅
- 카드 컴포넌트 이미지 사이즈 변경 (기존: 꽉 차는 것 → 수정 후: 이미지의 비율이 깨지지 않도록)
- 뉴스에 사용되는 이미지 컴포넌트에서 `sizes` 속성 지정하여 경고 콘솔 뜨지 않도록 함
> [QJ5-131] 뉴스 페이지에서 발생하는 버그 수정

- src/actions/stock.ts
- src/app/[lang]/(home)/home/news.tsx
- src/app/[lang]/(home)/home/page.tsx
- src/app/[lang]/(home)/page.tsx
- src/app/[lang]/(report)/report/[stockReutersCode]/layout.tsx
- src/app/[lang]/(report)/report/_components/AccumulationBarChart.tsx
- src/app/[lang]/(report)/report/_components/MyStockToggleInReport.tsx
- src/app/[lang]/(report)/report/_components/ReportHeader.tsx
- src/app/[lang]/(report)/report/_components/StockAIReport.tsx
- src/app/[lang]/(report)/report/_components/StockChart.tsx
- src/app/[lang]/(report)/report/_components/StockChartSection.tsx
- src/app/[lang]/(report)/report/_components/StockDetail.tsx
- src/app/[lang]/(report)/report/_components/StockDetailHeader.tsx
- src/app/[lang]/(report)/report/_components/skeleton/StockDetailSkeleton.tsx
- src/app/api/chat/route.ts
- src/app/api/stock/[reutersCode]/description/route.ts
- src/components/common/ChatBox.tsx
- src/components/common/CircleSpinner.tsx
- src/components/common/TextMore.tsx
- src/dictionaries/ch.json
- src/dictionaries/en.json
- src/dictionaries/fr.json
- src/dictionaries/jp.json
- src/dictionaries/ko.json
- src/hooks/use-stock-price.ts
- src/providers/ReportProvider.tsx
- src/stores/useReportStore.ts
- src/types/StockDataType.ts
- 설명 더보기 기능 추가
- 주식 가격 차트 하단 거래량 차트 추가
- 서버 컴포넌트로 변경 가능한 컴포넌트는 최대한 서버 컴포넌트로 변경
( 클라이언트 컴포넌트 | 서버 컴포넌트로 분리해서 서버 컴포넌트 하위 요소에 클라이언트 컴포넌트가 동작하도록 변경 )
- revalidate 추가로 일부 컴포넌트 렌더링 최적화
- 챗봇 다국어 기능 추가
> [QJ5-138] AI 툴에 설명 API 추가 + 리포트 페이지 최적화

- src/app/[lang]/(discovery)/discovery/_components/DiscoveryInput.tsx
- src/app/[lang]/(discovery)/discovery/_components/SearchItem.tsx
- src/app/[lang]/(home)/home/news.tsx
- src/app/[lang]/(mystock)/mystock/_components/MyStockRecentSearches.tsx
- src/components/common/Modal.tsx
- src/components/common/SearchBox.tsx
검색 하고 다른 페이지 이동한 후 다시 검색 창으로 돌아오면 검색 창에 인코딩 된 값이 들어가는 버그 수정
> [QJ5-149] 발견, 관심주식 페이지 검색 버그 수정

- src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
- src/app/[lang]/(mypage)/mypage/page.tsx
- src/components/common/InvestPropensity.tsx
마이페이지에서 데이터를 받아올 때 투자성향데이터가 기존 유저는 동의하지 않은 경우, `undefined`로 들어갔기 때문에 이 부분 따로 처리해주었습니다. (새로 가입하는 유저는 `undefined`로 들어가지 않도록 처리해두었습니다!)
프로필설정페이지에서 사용하는 투자성향 폼 `submit`함수는 반환값이 void라서 타입 추가해주었습니다!
> [QJ5-160] 투자성향데이터 에러 수정

- src/actions/news.ts
- src/app/[lang]/(news)/news/[newsId]/_components/RelatedNews.tsx
- src/app/[lang]/(news)/news/_components/NewsInfinityList.tsx
- src/components/common/List/NewsItem.tsx
- src/components/common/List/StockItem.tsx
- src/dictionaries/ch.json
- src/dictionaries/en.json
- src/dictionaries/fr.json
- src/dictionaries/jp.json
- src/dictionaries/ko.json
- src/hooks/useInfiniteNews.ts
뉴스페이지, 뉴스상세페이지 다국어 작업 완료
설정 언어에 따라 뉴스 api값을 반환하도록 설정해줬습니다!
(예솔님이 대부분 작업해주셨습니다!!👍🏻👍🏻)
https://github.com/user-attachments/assets/31a81313-3509-4fdf-ad1f-860fed7e2d9a
> [QJ5-144] 뉴스 다국어 작업

- src/app/[lang]/(auth)/withdraw/page.tsx
- src/app/[lang]/(mypage)/mypage/layout.tsx
- src/app/[lang]/layout.tsx
- src/dictionaries/ch.json
- src/dictionaries/en.json
- src/dictionaries/fr.json
- src/dictionaries/jp.json
- src/dictionaries/ko.json
- 마이페이지 레이아웃에 메타 데이터를 추가하였습니다. 
- 루트 레이아웃 메타태그는 정민님이 먼저 작업해주셔서 삭제했습니다!🤩
> [QJ5-169] 마이페이지 메타 태그 추가

- src/utils/metadata.ts
- 로그인/회원가입 메타태그의 타이틀 적용되지 않아, URL로 노출 중
> [QJ5-177] 로그인/회원가입 메타데이터 타이틀 적용되지 않는 이슈 

- src/app/[lang]/(auth)/account/profile-setup/page.tsx
- src/utils/metadata.ts
- 클라이언트 컴포넌트내의 unstable_setRequestLocale 제거 
- 회원가입 페이지 하위 라우터 아잇나우 문구 적용
> [QJ5-178] 프로필 설정 프로필 설정 배포 이슈

- src/app/[lang]/not-found.tsx
- src/dictionaries/ch.json
- src/dictionaries/en.json
- src/dictionaries/fr.json
- src/dictionaries/jp.json
- src/dictionaries/ko.json
- not-found 페이지의 다국어 작업을 진행했습니다.
> [QJ5-186] not-found 페이지 다국어 작업
